#!/bin/bash

WEB_USER=banshee
WEB_HOST=banshee.fm
WEB_PATH=web/download.banshee.fm/banshee/${RELEASE_TYPE}
WEB_DOAP_PATH=web/download.banshee.fm/banshee

#OSX_USER=Build
#OSX_HOST=164.99.121.141
#OSX_BUILD_DIR='$HOME'/banshee-build/build/osx
#OSX_GIT=/usr/local/git/bin/git
