// redirect.c - a CGI proxy to the Amazon MP3 store
//
// Authors:
//   Aaron Bockover <abockover@novell.com>
//
// Copyright 2010 Novell, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// ------------------------------------------------------------------------
//
// Provides IP-based geolocation to an appropriate Amazon MP3 storefront,
// supporting the home and search functions. Injects the Banshee Project's
// Amazon Affiliate ID into the redirected URLs. 100% of all revenue
// generated by this affiliate ID goes to the GNOME Foundation.
//
// The proxy itself is very simple and lame. It's written to be fast and
// short lived (memory is not explicitly released).

#include <GeoIP.h>
#include <glib.h>
#include <stdlib.h>

// We ask that no one change this. ALL (100%) revenue generated by this
// affiliate ID is sent directly to the GNOME Foundation. The GNOME
// Foundation controls/owns this affiliate ID. Please help support Free
// Software through the GNOME Foundation!
#define AMAZON_AFFILIATE_ID "banshee-20"

gint
main (gint argc, gchar **argv)
{
    GeoIP *geoip;
    const gchar *remote_addr;
    const gchar *path_info;
    gchar **path_parts;
    const gchar *country;
    gchar *action;
    gchar *input;
    gchar *domain;
    gchar *p;
    gchar *dest_url;

    remote_addr = g_getenv ("REMOTE_ADDR");

    path_parts = g_strsplit (path_info = g_getenv ("PATH_INFO"), "/", 4);
    if (path_parts == NULL ||
        path_parts[0] == NULL ||
        (country = path_parts[1]) == NULL) {
        return 1;
    }

    input = NULL;
    action = NULL;
    if ((action = path_parts[2]) != NULL) {
        input = path_parts[3];
    }
    
    if ((p = strrchr (remote_addr, ':')) != NULL) {
        remote_addr = p + 1;
    }

    if (strcmp (country, "geo") == 0) {
        geoip = GeoIP_new (GEOIP_STANDARD);
        country = GeoIP_country_code_by_name (geoip, remote_addr);
    }

    if (country == NULL || strcmp (country, "US") == 0) {
        domain = "com";
    } else if (strcmp (country, "FR") == 0) {
        domain = "fr";
    } else if (strcmp (country, "UK") == 0) {
        domain = "co.uk";
    } else if (strcmp (country, "DE") == 0 ||
        strcmp (country, "CH") == 0 ||
        strcmp (country, "AT") == 0) {
        domain = "de";
    } else if (strcmp (country, "JP") == 0) {
        domain = "co.jp";
    } else {
        domain = "com";
    } 

    if (input == NULL || action == NULL || strcmp (action, "home") == 0) {
        dest_url = g_strdup_printf ("http://www.amazon.%s/mp3/", domain);
    } else if (strcmp (action, "search") == 0) {
        dest_url = g_strdup_printf ("http://www.amazon.%s/s/ref=nb_sb_noss?url=search-alias%%3Ddigital-music&field-keywords=%s", domain, input);
    } else {
        return 1;
    }

    printf ("Location: http://www.amazon.com/gp/redirect.html?ie=UTF8&location=%s&tag="
        AMAZON_AFFILIATE_ID "\n\n",
        g_uri_escape_string (dest_url, NULL, TRUE));

    return 0;
}
