#!/usr/bin/env perl

open (IN, '../src/Core/Banshee.Core/Resources/contributors.xml');

my @names;
while (my $line = readline(IN)) {
    if ($line =~ m/>([^<]+)</) {
        push @names, $1;
    }
}
@names= sort (@names);

my $i = 80;
my $indent = 4;

foreach my $name (@names) {
    if ($i + length($name) + 2 >= 80) {
        $i = $indent - 1;
        print "\n";
        print ' ' x $indent;
    }

    print $name;
    print ", ";
    $i += length ($name) + 2;
}
print "\n";

close (IN);
