#!/usr/bin/env python

import sys
import re

times = {}
grand_total = 0

for line in open (sys.argv[1]):
	match = re.match ('^\[.+\] (.+) service started \((\w+), ([0-9\.]+)s\)',
		line.rstrip ('\r\n'))
	if match:
		type = match.group (1)
		if type not in times:
			times[type] = []
		times[type].append ((match.group (2), float (match.group (3))))

for k, v in times.iteritems ():
	set_total = 0
	print '%s Services:\n' % k
	v.sort (lambda a, b: -cmp (a[1], b[1]))
	for service, time in v:
		set_total = set_total + time
		print '\t%.8f\t%s' % (time, service)
	print '\t----------\t-----'
	print '\t%.8f\tTotal\n' % set_total
	grand_total = grand_total + set_total

print '\n\t%.8f\tGrand Total' % grand_total
